---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:
      
- hosts: all
  become: yes
  strategy: free
  roles:
  - { role: node-exporter, when: "node_exporter_enabled|default(false)|bool == true" }
  - vpnpeer_setup
  - polkadot_common

- hosts: all
  become: yes
  roles:
  - vpnpeer
  - common

- hosts: public
  become: yes
  roles:
  - polkadot_public

- hosts: validator
  become: yes
  roles:
  - polkadot_validator
  - polkadot_validator_session_info
